language: objective-c
os: osx
osx_image: xcode9.3
xcode_project: Screenshot-OCR.xcodeproj
xcode_scheme: Screenshot-OCR
before_install:
    - brew update
    - brew outdated xctool || brew upgrade xctool
