language: objective-c
os: osx
osx_image: xcode9.3
xcode_project: Screenshot-OCR.xcodeproj
xcode_scheme: Screenshot-OCR
script:
    - xcodebuild -showsdks
    - xcodebuild clean build
        CODE_SIGNING_REQUIRED=NO
        CODE_SIGN_IDENTITY=
        -destination 'platform=OS X'
        -sdk macosx10.13
        -project Screenshot-OCR.xcodeproj
        -scheme Screenshot-OCR
